# <company> BitBucket Pipeline: Pushes stuff to remote customer git repo
image: atlassian/default-image:2

pipelines:
  branches:
    master:
    - step:
        script:
          - echo "Push to master remote ..."
          - git push $remotegit master
          - echo "*done*"

  default:
    - step:
        script:
          - echo "Nothing to do for now"
