# <company> BitBucket Pipeline: Pushes stuff to remote customer git repo
# if you specify no image, latest "atlassian/default-image:latest" will be used, see https://confluence.atlassian.com/bitbucket/use-docker-images-as-build-environments-792298897.html
# image: atlassian/default-image:2

pipelines:
  branches:
    master:
    - step:
        script:
          - echo "Push to master remote ..."
          - echo "SSH ..."
          - ssh $ssh_user_host $ssh_params -t 'echo "Starting"; uname -a; touch /tmp/bitbucket-pipeline; echo "*done*"'
          - echo "SSH done"
          - git push $remotegit master
          - echo "*done*"

  default:
    - step:
        script:
          - echo "Nothing to do for now"
